name: Build & Deploy Azure Functions
env:
    OUTPUT_PATH: ${{ github.workspace }}/.output
    DOTNET_VERSION: "3.1.100"
    FUNC_APP_NAME: blogimagegenerator

on:
    push:
        branches:
            - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: "Checkout"
          uses: actions/checkout@master

        - name: Setup Dotnet ${{ env.DOTNET_VERSION }}
          uses: actions/setup-dotnet@v1
          with:
              dotnet-version: ${{ env.DOTNET_VERSION }}

        - name: Publish functions
          run: dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }}
          working-directory: Serverless

        - name: Package functions
          uses: actions/upload-artifact@v1
          with:
            name: functions
            path: ${{ env.OUTPUT_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download website
        uses: actions/download-artifact@v1
        with:
          name: functions
          path: ${{ env.OUTPUT_PATH }}

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  
